name: dependabot-manual
# curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token TOKEN" -d '{"ref":"master", "inputs":{ "pr-number": "PR_NUMBER"}}' https://api.github.com/repos/finzzz/tldr/actions/workflows/dependabot-manual.yml/dispatches

on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.DEPENDABOT }}
          pr-number: ${{ github.event.inputs.pr-number }}
